/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrunlerRouteImport } from './routes/urunler'
import { Route as SiparisTakipRouteImport } from './routes/siparis-takip'
import { Route as SepetRouteImport } from './routes/sepet'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as ProfilRouteRouteImport } from './routes/profil/route'
import { Route as LegalRouteRouteImport } from './routes/legal/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilIndexRouteImport } from './routes/profil/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as UrunPayRouteImport } from './routes/urun/pay'
import { Route as UrunIdRouteImport } from './routes/urun/$id'
import { Route as ProfilCartRouteImport } from './routes/profil/cart'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as PaymentFailedRouteImport } from './routes/payment/failed'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as DashboardOrdersOrderIdRouteImport } from './routes/dashboard/orders/$orderId'

const UrunlerRoute = UrunlerRouteImport.update({
  id: '/urunler',
  path: '/urunler',
  getParentRoute: () => rootRouteImport,
} as any)
const SiparisTakipRoute = SiparisTakipRouteImport.update({
  id: '/siparis-takip',
  path: '/siparis-takip',
  getParentRoute: () => rootRouteImport,
} as any)
const SepetRoute = SepetRouteImport.update({
  id: '/sepet',
  path: '/sepet',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRouteRoute = ProfilRouteRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRouteRoute = LegalRouteRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIndexRoute = ProfilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfilRouteRoute,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const UrunPayRoute = UrunPayRouteImport.update({
  id: '/urun/pay',
  path: '/urun/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunIdRoute = UrunIdRouteImport.update({
  id: '/urun/$id',
  path: '/urun/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilCartRoute = ProfilCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ProfilRouteRoute,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment/failed',
  path: '/payment/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersOrderIdRoute = DashboardOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/legal': typeof LegalRouteRouteWithChildren
  '/profil': typeof ProfilRouteRouteWithChildren
  '/iletisim': typeof IletisimRoute
  '/login': typeof LoginRoute
  '/sepet': typeof SepetRoute
  '/siparis-takip': typeof SiparisTakipRoute
  '/urunler': typeof UrunlerRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/profil/cart': typeof ProfilCartRoute
  '/urun/$id': typeof UrunIdRoute
  '/urun/pay': typeof UrunPayRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/profil/': typeof ProfilIndexRoute
  '/dashboard/orders/$orderId': typeof DashboardOrdersOrderIdRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iletisim': typeof IletisimRoute
  '/login': typeof LoginRoute
  '/sepet': typeof SepetRoute
  '/siparis-takip': typeof SiparisTakipRoute
  '/urunler': typeof UrunlerRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/profil/cart': typeof ProfilCartRoute
  '/urun/$id': typeof UrunIdRoute
  '/urun/pay': typeof UrunPayRoute
  '/dashboard': typeof DashboardIndexRoute
  '/legal': typeof LegalIndexRoute
  '/profil': typeof ProfilIndexRoute
  '/dashboard/orders/$orderId': typeof DashboardOrdersOrderIdRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/legal': typeof LegalRouteRouteWithChildren
  '/profil': typeof ProfilRouteRouteWithChildren
  '/iletisim': typeof IletisimRoute
  '/login': typeof LoginRoute
  '/sepet': typeof SepetRoute
  '/siparis-takip': typeof SiparisTakipRoute
  '/urunler': typeof UrunlerRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/profil/cart': typeof ProfilCartRoute
  '/urun/$id': typeof UrunIdRoute
  '/urun/pay': typeof UrunPayRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/profil/': typeof ProfilIndexRoute
  '/dashboard/orders/$orderId': typeof DashboardOrdersOrderIdRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/legal'
    | '/profil'
    | '/iletisim'
    | '/login'
    | '/sepet'
    | '/siparis-takip'
    | '/urunler'
    | '/dashboard/customers'
    | '/dashboard/products'
    | '/payment/failed'
    | '/payment/success'
    | '/profil/cart'
    | '/urun/$id'
    | '/urun/pay'
    | '/dashboard/'
    | '/legal/'
    | '/profil/'
    | '/dashboard/orders/$orderId'
    | '/dashboard/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/iletisim'
    | '/login'
    | '/sepet'
    | '/siparis-takip'
    | '/urunler'
    | '/dashboard/customers'
    | '/dashboard/products'
    | '/payment/failed'
    | '/payment/success'
    | '/profil/cart'
    | '/urun/$id'
    | '/urun/pay'
    | '/dashboard'
    | '/legal'
    | '/profil'
    | '/dashboard/orders/$orderId'
    | '/dashboard/orders'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/legal'
    | '/profil'
    | '/iletisim'
    | '/login'
    | '/sepet'
    | '/siparis-takip'
    | '/urunler'
    | '/dashboard/customers'
    | '/dashboard/products'
    | '/payment/failed'
    | '/payment/success'
    | '/profil/cart'
    | '/urun/$id'
    | '/urun/pay'
    | '/dashboard/'
    | '/legal/'
    | '/profil/'
    | '/dashboard/orders/$orderId'
    | '/dashboard/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LegalRouteRoute: typeof LegalRouteRouteWithChildren
  ProfilRouteRoute: typeof ProfilRouteRouteWithChildren
  IletisimRoute: typeof IletisimRoute
  LoginRoute: typeof LoginRoute
  SepetRoute: typeof SepetRoute
  SiparisTakipRoute: typeof SiparisTakipRoute
  UrunlerRoute: typeof UrunlerRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  UrunIdRoute: typeof UrunIdRoute
  UrunPayRoute: typeof UrunPayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urunler': {
      id: '/urunler'
      path: '/urunler'
      fullPath: '/urunler'
      preLoaderRoute: typeof UrunlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siparis-takip': {
      id: '/siparis-takip'
      path: '/siparis-takip'
      fullPath: '/siparis-takip'
      preLoaderRoute: typeof SiparisTakipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sepet': {
      id: '/sepet'
      path: '/sepet'
      fullPath: '/sepet'
      preLoaderRoute: typeof SepetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/': {
      id: '/profil/'
      path: '/'
      fullPath: '/profil/'
      preLoaderRoute: typeof ProfilIndexRouteImport
      parentRoute: typeof ProfilRouteRoute
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/urun/pay': {
      id: '/urun/pay'
      path: '/urun/pay'
      fullPath: '/urun/pay'
      preLoaderRoute: typeof UrunPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urun/$id': {
      id: '/urun/$id'
      path: '/urun/$id'
      fullPath: '/urun/$id'
      preLoaderRoute: typeof UrunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/cart': {
      id: '/profil/cart'
      path: '/cart'
      fullPath: '/profil/cart'
      preLoaderRoute: typeof ProfilCartRouteImport
      parentRoute: typeof ProfilRouteRoute
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/$orderId': {
      id: '/dashboard/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/dashboard/orders/$orderId'
      preLoaderRoute: typeof DashboardOrdersOrderIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOrdersOrderIdRoute: typeof DashboardOrdersOrderIdRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOrdersOrderIdRoute: DashboardOrdersOrderIdRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LegalRouteRouteChildren {
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteRouteChildren: LegalRouteRouteChildren = {
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteRouteWithChildren = LegalRouteRoute._addFileChildren(
  LegalRouteRouteChildren,
)

interface ProfilRouteRouteChildren {
  ProfilCartRoute: typeof ProfilCartRoute
  ProfilIndexRoute: typeof ProfilIndexRoute
}

const ProfilRouteRouteChildren: ProfilRouteRouteChildren = {
  ProfilCartRoute: ProfilCartRoute,
  ProfilIndexRoute: ProfilIndexRoute,
}

const ProfilRouteRouteWithChildren = ProfilRouteRoute._addFileChildren(
  ProfilRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LegalRouteRoute: LegalRouteRouteWithChildren,
  ProfilRouteRoute: ProfilRouteRouteWithChildren,
  IletisimRoute: IletisimRoute,
  LoginRoute: LoginRoute,
  SepetRoute: SepetRoute,
  SiparisTakipRoute: SiparisTakipRoute,
  UrunlerRoute: UrunlerRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  UrunIdRoute: UrunIdRoute,
  UrunPayRoute: UrunPayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
